/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI_RX_ISR.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "SPIS_2.h"
#include "SPIS_2_PVT.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "Button_1_aliases.h"
#include "Button_1.h"
#include "SPIS_2_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

