/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "isr_uart_rx.h"
#include "ADC_SAR_1.h"
#include "Pin_ADC_in_aliases.h"
#include "Pin_ADC_in.h"
#include "Timer_1.h"
#include "clock_1.h"
#include "A2_aliases.h"
#include "A2.h"
#include "B2_aliases.h"
#include "B2.h"
#include "B1_aliases.h"
#include "B1.h"
#include "A1_aliases.h"
#include "A1.h"
#include "PWM_1.h"
#include "PWM_Out_aliases.h"
#include "PWM_Out.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_ExtVref_aliases.h"
#include "ADC_SAR_1_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

